# Mutation to create a movie
mutation CreateMovie($title: String!, $genre: String!, $imageUrl: String!) {
  movie_insert(data: { title: $title, genre: $genre, imageUrl: $imageUrl })
}

# Mutation to add a review for a movie
mutation AddReview($movieId: UUID!, $rating: Int!, $reviewText: String!) {
  review_upsert(
    data: { movieId: $movieId, rating: $rating, reviewText: $reviewText }
  )
} #
